/// add a new icon state to statdesc.ids ///
DEFINE_ACTION_FUNCTION resolve_statdesc
  INT_VAR desc_index = 0
  STR_VAR new_icon = ~blah~
  RET new_state_index
BEGIN
  OUTER_SET "new_state_index" = 0
  // OUTER_SET "last_state_index" = 0
  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 rows
    FOR ( index = 0 ; index < rows ; ++index) BEGIN
      READ_2DA_ENTRY "%index%" 0 3 "statdesc_index"
      READ_2DA_ENTRY "%index%" 1 3 "statdesc_desc"
      READ_2DA_ENTRY "%index%" 2 3 "statdesc_bam"
      // SET "last_state_index" = "%statdesc_index%"
      PATCH_IF ("%statdesc_bam%" STRING_COMPARE_CASE "%new_icon%" = 0) BEGIN
        SET "new_state_index" = "%statdesc_index%"
      END
    END
    PATCH_IF (new_state_index = 0) BEGIN
      SET "new_state_index" = %rows% + 1
      INSERT_2DA_ROW rows 3 ~%new_state_index%    %desc_index%    %new_icon%~
    END
  BUT_ONLY
END
